passwords = [
    "xwjgxtmrzxzmkx",
    "rrrkrgr",
    "vvfvvvn",
    "pxmrtmbmqmcldmmm",
    "bsshsszslssssslqdsss",
    "gggggggggzgvg",
    "dntnrng",
    "xrjflbmjszzjbjjh",
    "frxrrrfjnmr",
    "hplhgcsphh",
    "wwwwz",
    "ggdggnggg",
    "cccc",
    "kjgmkkfwxkwqkkgfnv",
    "xpwhdjhhjhrdjkhfh",
    "vgggggdhgsp",
    "rtdcrthphrkzxh",
    "jjjjjjstjjjjhjjjjj",
    "kkkkpkkqkv",
    "sssssj",
    "hdbmbpswddwkkr",
    "ssscssnss",
    "zzzzzzzftz",
    "glwvkgtn",
    "nnnnnnnnnnn",
    "lzzzzfhj",
    "llllllltn",
    "dpcppp",
    "hcfdltbgt",
    "rrdrrqrrrrrsbrrr",
    "lllltllllllllllllrll",
    "vzzzpzfzdzzzzzzfczz",
    "ffffb",
    "csssssjrbdsgs",
    "rrrrrrbrrrjzdrrrcrr",
    "fdzxdj",
    "cclcccccccccmc",
    "zzvszszjbnzzz",
    "ssqshwsss",
    "hxxxxjvdxcqplp",
    "mxtrtttttttttt",
    "wmwwwnbmtw",
    "xsczxd",
    "pwvtgkwwwrpjr",
    "wwwwwwwwj",
    "hhhhbhhhschhh",
    "tlwx",
    "lhzjwwwwmv",
    "ppppglprp",
    "jqmmmmmzmmmmmjmbxmw",
    "zhggpgrrlctggg",
    "pltbcznlvtzgzczzchbz",
    "jttttgtttttt",
    "kkkkkkkkkkk",
    "xxxxxxxxxxxxxxxxxxwr",
    "llllllflllllxpllzl",
    "mmjmmmmmmvms",
    "cdxvxczcc",
    "nnnnfnvpncn",
    "zszzzrzczxzfzzzzlz",
    "kkkdkkkkfk",
    "mmgmmqfgmmtmm",
    "tdmmcs",
    "nkfpnncncnnntmtc",
    "vwhwf",
    "wwfwwwqhwwwwcwwww",
    "tkqrtqqsqkwq",
    "ptpppppppd",
    "cnncnmnf",
    "kkjdsnsqkgprtqb",
    "nplnnnnnnnmnn",
    "rrkrzrr",
    "zzzzsq",
    "rrrrrrrrrrrrrrrrrx",
    "rcccdcclc",
    "vcccccccbc",
    "xxxxcbxxxm",
    "cccfn",
    "cccccnctc",
    "flrhfzwllm",
    "fllfllrklx",
    "jrjkrjjjjxgjqj",
    "dsxvmvvjtsc",
    "bsqvdghvnzdfvjcfvvv",
    "mmmmmmmmmmpm",
    "qqgqkcccsgqqjspj",
    "nvsrc",
    "nnnnnnnnnnnbnms",
    "mmbm",
    "hhbhhhhhhhhhhhhhhhh",
    "kkkkbknkjv",
    "ggvgggfgbgvvzjgxghgg",
    "zzzz",
    "wwwhww",
    "jjjjjjjjtjjjjw",
    "jjbljsj",
    "bwtkbttwqvwk",
    "lllpjl",
    "ggfmggggsrggggg",
    "ttwzxl",
    "kkwtbckkk",
    "rbgrrhrrrrrr",
    "ggggggsggglnggg",
    "bbbwjs",
    "xkjmdmm",
    "gggggwgw",
    "vrvvvqvvpvzvvvvrhqv",
    "hsnjsrsdxpjswsxsss",
    "rnhnrrsrrrrr",
    "ddnd",
    "mmtxkcdrvcmx",
    "kxkkkskkkkkktkkmkc",
    "vfxhhshhvhhbhr",
    "wtrcckttcqrj",
    "wnqcqqxw",
    "sqsssslsssssssssss",
    "mwvpppzp",
    "qlvnvv",
    "lzzzzzzzznt",
    "qwqqqqqqqqqqqfqqr",
    "dddddzddddddddlddddt",
    "fvsqwbnqmbnmgcm",
    "fncnfdjzcxwbpcrn",
    "jsxzzszzqtwzmcznfs",
    "glxxxxrxfxxwl",
    "pdbvhwjwnbdwbrbbjwf",
    "hhthhhvvt",
    "pfffffxffpbf",
    "ndtlxnnnqdmcnv",
    "sssssswssdshssss",
    "ssssssssssqsssss",
    "sssss",
    "ggggg",
    "ccjv",
    "rrrngfwhslsbpvbmwnn",
    "nxnbnnnbxnnn",
    "fggdddpgslqgdwhdndw",
    "hhzzghhfdchhjnm",
    "cccccccnc",
    "hhhhhhhhll",
    "nwfwwwzwvrbmwwww",
    "kkkksjkkskqtkkmkknks",
    "fffwfffbkc",
    "gcfkvvvvfvv",
    "llflftlmlglc",
    "llldljllgsbl",
    "svcsnlshppvrxzghhzg",
    "dddwdzvmddd",
    "kpmmjpmmmdz",
    "nnnnnnnnnnnnns",
    "bkbbbbbbbbbbbbbd",
    "jghfggh",
    "mmmmmmrmmmm",
    "pbjjpjnjxjjfsjzsjps",
    "rrrrrrrr",
    "vvvvvvvbbvvvvvw",
    "tpppppprzpspbpplppr",
    "wbhhzxhllh",
    "nvbcckcpccrtccwccsc",
    "jjjjjjjjjjjzhj",
    "dznzpnxzppl",
    "jrrrsrrrrr",
    "gjqjcqqqqsqfqqq",
    "kkkkkkkkkkkg",
    "mmtmmmmmmmmmmmmmm",
    "khgttqtcltshttwqgt",
    "bbbbbbbbbbbbbqb",
    "fffqfmffpnffffg",
    "jlghwmmrbdvdfjbj",
    "vvkbvvrv",
    "qmcgxcshgwmfm",
    "cmmmzfmcmmzmmmmjmr",
    "hnnbnnnw",
    "mvdtmstm",
    "bcrmmjbpmmmsdnrmm",
    "wwwww",
    "jjjjjjjjjjjrjhj",
    "ghhczbhblx",
    "vmvvvvvggvjpvchvvpc",
    "ffwfflghpwfl",
    "krkmjkgkzcckjbkkk",
    "cfcp",
    "ztzzzdzzzzzzzzzzt",
    "bmrpdwphzqvppktz",
    "jjvjtj",
    "hvchvhhhhbhthlhhhhhh",
    "kqjp",
    "fsxxxkxxbpkxmhlrdtfx",
    "wwpxwwwwwwgtwwcwwww",
    "wppxkq",
    "xxxzxxxbxxxxxxvxs",
    "qvqqqqxqqqqfqqq",
    "qqqqqqqvqqqq",
    "mmmmmmmjmn",
    "ttttrttttsttttttttt",
    "hhhhhqhjlvhhqhhwh",
    "ssssshsst",
    "qvvtvsvcmzvvnpgvv",
    "djcpndppsdddfdsdd",
    "dgzwvbrzzbgw",
    "kwkl",
    "dkdmdsdwdzvlpv",
    "hhhhhhhhhhh",
    "ffffffffff",
    "ssddddxp",
    "jjjjjjjjjjjjjjjjjsj",
    "mkmmrmmlrzsmgm",
    "kkkkkkknk",
    "wwwwj",
    "xslmsfgsssssmslsstqd",
    "zzzch",
    "jjjjjjjjjjj",
    "hjhhkdh",
    "vvvvglvvdvvvvv",
    "shqnjdqqq",
    "dqqqq",
    "zzznzzz",
    "vwsfsxssd",
    "sffffv",
    "xllbbdb",
    "rtzjqkpnkjlrhjcjqj",
    "wwwwwwwfwxz",
    "sggtlggswf",
    "nnbnnncnnsgnnmknn",
    "cclcnccctcrcxqmd",
    "lmllxwpl",
    "pppppppcpkdp",
    "zwwx",
    "nlfpgfzqkzn",
    "vbwwgwvwrwlwwmwwwjw",
    "vzfjgjrkzdrxqfh",
    "frrq",
    "vkkkkk",
    "pndlftgdpdhld",
    "prrvrrrrfrrrrr",
    "fmmxmmmmmmm",
    "xcpxc",
    "rhbndvjnnsnfnwnnm",
    "fkzwxtqmgm",
    "bpppqpppppplpppphpsr",
    "ggggthggggpjgqgslggq",
    "mzmmxcfwmdpz",
    "tttttttptttts",
    "qqvqqqcqq",
    "jsjjjjccjwjcjjj",
    "rdlrrrrrrr",
    "wrrzsrcrgcbrhqvrhlp",
    "jjxjjzhxj",
    "mmmmmmmm",
    "mldvdmxmbk",
    "ffffnffffkqf",
    "ffffsfffftfffkffn",
    "fbwbhvx",
    "ggggggggthgggggsvd",
    "cvsbw",
    "qltgnfghgcrgpnzdsvng",
    "ppjbpnppxg",
    "lgjrzwdvdnwvrnj",
    "cdcc",
    "llflrhlllgklh",
    "tppp",
    "gggggggvggggggggg",
    "fhfdffftfbggpkfgf",
    "bbbbbbbbbbbbbbbbbbbb",
    "thqvvkvlwvdvjzzst",
    "ppppppppppppptc",
    "tkttczttttsttmcnltm",
    "nvxl",
    "fpflfwftk",
    "xhhhhh",
    "tttttttttttttttlv",
    "jjjjjjjjjsjjjjjjd",
    "jcgs",
    "qsqqjhqndsqkqqpvqqr",
    "tnpplcmdpfn",
    "crvmk",
    "tsmzcgddnddddrdxsq",
    "rlfcpctpncv",
    "tkzfhffdf",
    "sssmsscfvsssdsg",
    "ssjsssjrscsss",
    "fffffffkfff",
    "jqtdhpknkkk",
    "tttttttttttf",
    "swjbddfpfbntmprdd",
    "dvvvvvvvvvvvvvvvkvvv",
    "kjjcqjj",
    "dddddddcddld",
    "fffffffffffffffk",
    "nxxxxxxn",
    "pppppppppppppppppr",
    "ktkjkkkkfvklkz",
    "hhhhhhhhchhhhhhhhh",
    "hvkvvvvvvvvvvvvvvqc",
    "xzbxgsxshgl",
    "ppsjpglptchpzbdhj",
    "nnnnnnnc",
    "jhtjjjjj",
    "vnblqbxkbbwb",
    "czzzcztsz",
    "wxpvxxxfxfxx",
    "wwwwwwwwwgwwww",
    "cntkkq",
    "vljplljlllllllll",
    "tfmvst",
    "rddddddwd",
    "bhvwhl",
    "ccsgccncwgjtcbhccckk",
    "rrrrmr",
    "hcrhhjrbhh",
    "xndshswk",
    "mmrqmmlp",
    "nnnbfpmnfnknxnndn",
    "fvffffb",
    "vhhhhhtk",
    "jjjjjwjjs",
    "rwrrrr",
    "tlzk",
    "kkkkkkk",
    "rqqqqqwflqqjqq",
    "llllglll",
    "rrkrrxrmrrrrrc",
    "lrwpzvhhcwtbrwwpwww",
    "kbjhskpbrwqpbcbbkb",
    "ddddbddhdddddddddmg",
    "nnnnnnnntnnnnhf",
    "cgjpktthdbfxrclqwzpl",
    "wwwwwbfwzwcwcwz",
    "tfhssgrsnbssfl",
    "wdkwkdlslbllllgzfm",
    "jhhhhhhhhhhhthhhhh",
    "wwvwwwwwrwwww",
    "rgrdrx",
    "dnxckkwpttv",
    "cgqxrszcckcd",
    "qkchpbqqtrtdztrq",
    "ddddsddddd",
    "pppppgppppqpppppppp",
    "lllhlllll",
    "hhhhhkhvwbhmh",
    "wwwwwwwwwwwnwwww",
    "jhcd",
    "nnnnnnnnnnnnndnnmnn",
    "dllpddkdd",
    "nnnnnkp",
    "vvbcvrvvkmvvsv",
    "jjjjcjs",
    "ldllllllll",
    "rxxxx",
    "qqqqqqqqqqqlqqqw",
    "mmmmmmmmmbmmzmbm",
    "skkkkkkkkq",
    "mghxpjzqdhjcbmdl",
    "ttsnwzbdj",
    "hqtkgtr",
    "twpknn",
    "wrldlsdl",
    "qlxncf",
    "dvsxs",
    "rktsrfwttttgwtzgft",
    "flsf",
    "cchczccccj",
    "bktw",
    "zdqxgrfkfhljhqhkgmfc",
    "sssssssssssssssvs",
    "plpfmnhsppnpwnx",
    "kkkkknkqkk",
    "nsqnssssvqsm",
    "jjjzjwczkjjjxjjcjjxj",
    "tnnbjjhtd",
    "llllllll",
    "cwsvrtszxrgh",
    "sxcxxxjxrxkxdxx",
    "mmxmbxmmdmmmmfmmfmm",
    "tllllwzlzlrbllllhnp",
    "kkkjkmkkkg",
    "wqqfmffffkp",
    "bbbbbmbbbbhbbdzbbtn",
    "hhhhdwbhhqrhhhdnxhr",
    "qfpnfrrrrz",
    "bbbbbbbbbbbbbbbbbbbb",
    "hwqccmwcctcnclcb",
    "clccccqqcccjczpgj",
    "jjjjjjjjjjjjjh",
    "jkfp",
    "qqxdcdjqg",
    "prrrrd",
    "llllllll",
    "nwlm",
    "vnknxncvgvrww",
    "sjnwfsksnszcglxs",
    "zzmkzzzzzntzjzbwpdjz",
    "ljjjjjjhjjwtjjjjdjwj",
    "dnnjlfkxls",
    "jmmqmdkjm",
    "mmmcmmmfsmmm",
    "ppppptpppphrpxpppp",
    "dfkfxdddldddddddlddp",
    "qqqqqqqqqqqwwgq",
    "tgggggmggggdg",
    "wwwwwwwwwbwjwwwwwt",
    "ttkttcttsrgrzlftpt",
    "jjjjjjjjjjjjjl",
    "ccccccczcccccccccs",
    "hjddddddddm",
    "lxjfp",
    "vvvvvvvvvvjv",
    "fmzblzvzm",
    "hhshhh",
    "ptvrtt",
    "kkkjzkckgckskpkk",
    "wwwwwwwwwwwftwdw",
    "jrhns",
    "pxmnzn",
    "bbbkbbbbbbwb",
    "rrjrqrrwrrrqv",
    "wwwwwwwwwwwwwww",
    "jsjjjp",
    "lhbbvmhwrhh",
    "qqqqqqqcxqqqqqqqqxwq",
    "llllllllllllllllxql",
    "jjljjn",
    "zzzzwnzlzggz",
    "tttttft",
    "ffffffffffnf",
    "hqbbbbbsbb",
    "stljwbxpw",
    "grxfpw",
    "wwwwpwwxw",
    "zqzzzzzvzzzzzzgz",
    "cckgrcmbpvbbw",
    "xqxbdddjds",
    "xxrxxx",
    "nnnnnnnnnnnnnndnn",
    "lqmxxxsxxfxxxxlx",
    "vssssshssmsk",
    "bmgkkmwmmzvmmmmmwflv",
    "thkvttsltnbgztt",
    "zzzzzzzzzzzzzzzzzz",
    "fjwfff",
    "ddddddddd",
    "kjkbkkckxkknqkkdc",
    "nsnckwnmn",
    "ptbtjqttwwtftpntdq",
    "wrhhrrrrrwrrrrvqrms",
    "zcrwhtccb",
    "nnwmmdmmmccv",
    "rtjjmjrjl",
    "dssjhsdmbksrks",
    "ccccclcccclccccccc",
    "qpzgqxdbssmzptrv",
    "bnsbbgdbggxbbszbm",
    "lrpstqvhhhhf",
    "tvssppwvss",
    "qqqhcd",
    "qxcqzccckxcpcxcw",
    "nbwdmspmmwbbmm",
    "xjrczrk",
    "wwwwwwwwwd",
    "hhhq",
    "bjmrrjsjthjnnjjxjjd",
    "srfwwfvf",
    "nbbzb",
    "nnnnn",
    "fxfnfffzpqffgdf",
    "kkpkkkpnkkmkjbkk",
    "jkkkkkkkwqk",
    "rzzzzs",
    "vvvtvvjq",
    "dzjnzczzpzgzzzx",
    "smsvbkswslssrdfjsc",
    "bwbbbbbbr",
    "kddbsmmbv",
    "bbbb",
    "rqrrdrrr",
    "mmmmmmzm",
    "xvnlfvhxqfql",
    "wfwj",
    "gqqcqg",
    "cqlxrq",
    "swwjjssjsstmqfssdh",
    "bqqq",
    "ccccbscgfc",
    "xxcxxxxxxxxxxxm",
    "fzfchfnrxfrdffhfl",
    "gggggggggggggjgpgg",
    "njkcngznn",
    "dddlqddddvddr",
    "xgcg",
    "sxsnsdmszwmsss",
    "qbcqspqqqkqrq",
    "xnnnnnnnnnnnnnnfnnn",
    "tssnssmsssssssssnhr",
    "vwvvv",
    "rzmhhjvqhht",
    "ttjdjftfctt",
    "nkkz",
    "vkvqkqq",
    "qxmjqxnxnblqnnqfgsrd",
    "hhhhhhhhhhhhhhghz",
    "jggpxdgwjpsrv",
    "xccccpccrcccc",
    "nfgbghqrljstggcgq",
    "gggggggggggggmggggg",
    "sssbsssssssssgs",
    "rcxvxcgddnhwd",
    "vccvdldqdgzltq",
    "zzdczzvrzzzzr",
    "ctgtttftqtrbt",
    "vvrvx",
    "wwwwwwwwwwwww",
    "hgccmcccc",
    "ssssssssssstssscsh",
    "zzflfrtdx",
    "vvlsvvvvkrc",
    "ddddwddddbdgdddwd",
    "gkbqbtrv",
    "cjdqvwhhththvx",
    "bbbkbrb",
    "ptkqdgsmbcmmblwp",
    "mlqqgsqqqfqkcqqxqq",
    "mdvqvmmxlmzmvmmdm",
    "hrrtrrrrrrrrrwlr",
    "jjjjhj",
    "dqpqqqqqqnzlqq",
    "dddnddnddtdddd",
    "dpddxtlqsqldrpddq",
    "szhzmmzzzzmzzzz",
    "mkxxqtbnnjgnvxnhhhc",
    "nknfrhpn",
    "dddddddgdddddddddd",
    "wwwwwwwwwwwwwwwww",
    "rttfdstqpdtg",
    "gghrfxbfshqssj",
    "bjjjjjjjhjjj",
    "xmpgppppppp",
    "vqpxrkmskfpnxq",
    "xxxxx",
    "bsxnwvpkphdppphpkwp",
    "xdddmzddfddc",
    "gvvvvvgvhnvw",
    "xxxxxwgsvmqnkxv",
    "ccscccccwccccccc",
    "nsvgwzdf",
    "wwwwwwwwwwwfwswcw",
    "qrrlwcrrwz",
    "hfnphfpjffstff",
    "hqjhmph",
    "cpxxxzcrbjxxxb",
    "kkkkktkkkkfkf",
    "gggghghsgwf",
    "sswswssggss",
    "qlllljllhlll",
    "cccwccrbcbccc",
    "xxxxxxg",
    "cwpww",
    "vvvvvvvvvwvv",
    "bbgl",
    "zbkbcbbbsbb",
    "tttttgtttttttktttt",
    "xxxxxxxxxxxxxqf",
    "kmrkkwmk",
    "mmxjmdrhzkmxxphjmz",
    "tnvtndw",
    "xxtxxtxzf",
    "nwmglfscmwrjtzp",
    "cnccckcckcwdc",
    "tvbmrqtchwblbqbbqbb",
    "fxxxxxxxjxx",
    "gggggkggx",
    "kkkkkfkpkqkwkkk",
    "chpvkvt",
    "rmbjmcrgrrfrtmblhw",
    "rnnwtn",
    "htclcjhjkdv",
    "wwwhhwwwrwwzww",
    "wwwwwwjwwwwwwwwvwtww",
    "phrwbwwmc",
    "qqqqqqqqqqqqqqqqx",
    "kzknsxkkgtvmwlfrmrg",
    "zbbbb",
    "hfclvvpc",
    "ctfthpmgznjnhgtth",
    "httttq",
    "wwxhgww",
    "fmtnmmm",
    "xnnchnzpsmcslvzcn",
    "mmmmcm",
    "rwsgcgvjmtxwkqtr",
    "mmmmmmmmmmmqmmmmmm",
    "sssggssssjsssmsss",
    "ppfppzppnvmpqdvpp",
    "wclwrlrdvh",
    "gggmkglggwgpgkmglt",
    "zzzbzpz",
    "qbqqlzpqg",
    "hhhhhhhhhrhhqhhhhhhh",
    "nfnxmsmhtmhsmmmmgmsl",
    "mkfmmm",
    "xrjdnjjjnjjcjjjjjj",
    "xwrjxhjxx",
    "zzzzzzzg",
    "kkkkkkkkkkkkkkkkk",
    "rnnxnnbwnsnnwn",
    "mkmmmsmm",
    "qqfxqqq",
    "hxmfbkszk",
    "rrrrrrr",
    "hhqzhhhh",
    "bhbvnrbrbblbbhh",
    "ddddddtdddvhddd",
    "fmfcfwf",
    "njqfxjjjqjjvdj",
    "fggkggzgghrv",
    "vbblbxpfrbjbgpwxb",
    "tzcdrktsqjsxssfsssh",
    "fffffffffcffffffffff",
    "pqpppppcpbwpppnprppk",
    "nnnmnnnnnnnnnnnsj",
    "kkkkkkkkkkkkkkktk",
    "wwwwwwwwwwm",
    "qqqqqq",
    "mmmmmxg",
    "mmvlggdmr",
    "wxdbmlcrlpnzmkfdfs",
    "zlxzgznqqfzsqtwc",
    "flvmfffjffbmgfzfgfp",
    "cgggqgxqgv",
    "rffvf",
    "vhhhhhhvhhvhhhhf",
    "vzdxxxgxtxzxxxqc",
    "rwwwwww",
    "brwrcrrkcsj",
    "jvqqqqqqqmq",
    "lvhvvwvvvvvlvlvvmv",
    "zzvzcwlzslhlzqsf",
    "sdknfxvwtcfcjgmv",
    "lqcwlllsllll",
    "dgklv",
    "qqqptfqqqqq",
    "mrmcmmmm",
    "rrrblg",
    "qcccccvntc",
    "mzbxmmmnhmqcmmqvbmcp",
    "ptvqx",
    "gpssssssgss",
    "bbbbbbbbbbbbbbbbbfb",
    "ffffgf",
    "lslglw",
    "ltzlllsdlmrllkvbztvr",
    "llllllllllllllnllll",
    "jjjjpjjjjjncj",
    "wfwgd",
    "vrrrzrr",
    "kkkjckkkgkbtvm",
    "kkkkkrckcrkk",
    "hpbjbvb",
    "ssssssvss",
    "mpxk",
    "xxxmrwhgxxxjx",
    "xxphxxxxx",
    "mdrlnnpnjndqgnkfwnnn",
    "qjwtbmkhtnxm",
    "xjjjjjbjqjjjjjjqjjjw",
    "pxxxxsxxsxx",
    "ttttrp",
    "fffffffffrkzf",
    "glsprkbp",
    "mmmmmmmmmmmsm",
    "zzszzzszzbzzzplzzz",
    "ccccchwccccccccccncb",
    "qzggglzlhshnrwt",
    "zzzzzzzzhzzwzc",
    "sssl",
    "fsqmwq",
    "zmzztzkzznmflqffz",
    "bwbbjbbbtlbbn",
    "nktszz",
    "nqjhjkb",
    "lrlllllllmllswlsl",
    "fjqvfff",
    "hwxghddqwwwwwww",
    "zgzfx",
    "vhhjhthh",
    "hhhhhhfhhhhhhhphhhh",
    "kkkkkkkkkkkkkkknx",
    "dllllllmlllfllf",
    "mtkwwwww",
    "zpkkgldk",
    "htmtjddddddqvddcd",
    "rvfbbwzdwcvvqv",
    "mmvmbvmmmsmmlmmm",
    "xpxppsgpbxp",
    "vffbszhvvrdfkxc",
    "lvrrlvvqqvr",
    "hdhhbhhzhhhhhhsbl",
    "fhgffgfrfqtf",
    "ssssfssdpssswf",
    "mmmmmmmmpzgmmm",
    "zlmllvwlllldl",
    "mmdmfmmdxbmxbmm",
    "fklssmffwzgqcvdpm",
    "cczcccccccccccc",
    "frtkfpffsfff",
    "ffffgffr",
    "mmxsmmmb",
    "mdmmmm",
    "hhdtmhwfpt",
    "dmrkdvddmdsdddbsgd",
    "cxccgcccc",
    "xcqvjvvsdvvvpv",
    "gltkjvddwjdkrln",
    "ggffllflfbfffqkfmf",
    "xkvcccccrmccccc",
    "qqsqqqqqqqqqqqqqfqmq",
    "ttttlttwtlt",
    "wffrd",
    "tvhvvqvrvvvvvvqvvf",
    "cccc",
    "zrzzpzlzzhsdxqqfx",
    "kkkkkkkkkk",
    "rvrrvrz",
    "wwwwwwwlwwwwncwvwjk",
    "qfhxqqgqqqsvcpr",
    "kflfffzff",
    "rtttttptlxsttt",
    "ttttttttttftbvqttt",
    "cckwlchltchcczgw",
    "ssssvsqnss",
    "mhhhhrhhh",
    "bbbbbbbbbbbbbbnb",
    "dpppppppppspppcps",
    "xbfjglklphtl",
    "vvvvbvwpvvvrv",
    "plhjkkqkskz",
    "zzzzzczzzzzk",
    "xvjljj",
    "rlrrrrrrzrrzrrr",
    "mqrkgpktbsqxg",
    "pzmzzxpnzxpgzzzhzz",
    "gslsskvgxssssnpj",
    "mmmmmmsmmmmmmk",
    "tnbdsfwdzxrkjdb",
    "hnxhzhmhhhhhwwb",
    "ccccccc",
    "bbbbbbbbbl",
    "jsjjj",
    "xmmnppbn",
    "mmmmmmmmmmmm",
    "jrgrcpvgctrrr",
    "gggr",
    "nhnpnnnnznnnnnnnknnm",
    "krkkf",
    "hhdhhhhhhhhghhkhx",
    "dqbcqqqqsqqzqqqqqqv",
    "ttrkttttstwttttqdt",
    "dhhhhhhhhjhtjhhhhhh",
    "ccccrccfc",
    "nvvnv",
    "prmmzmtmmmssdmmmmt",
    "rrrrrrrrrrrrrqfr",
    "djbbbbqjbdtbslbgbbmb",
    "wwwwwwwwwwwwww",
    "mbpcjqmmhpppkfmrbcww",
    "nxbjknms",
    "hxhcsldmxshdksvsss",
    "qqqqqqqpqcdqqtwkqvq",
    "tjlpcjjjjnj",
    "ssssskm",
    "tttttx",
    "pqmnqrlqchbjzqqvq",
    "qqqqqqqqqqhqrqqrqq",
    "jhkgkxkqfskg",
    "ffvffmfffffffsffqm",
    "xxfxhfxx",
    "ktbv",
    "wjtwxvxctrcttb",
    "shssg",
    "skkzbdpzdkzzz",
    "rlfffqft",
    "fsrcnjsgsmgs",
    "vvvvvvvvvvvvvvvvvvv",
    "kklmq",
    "hhhhhlvghwkhrfzhxh",
    "nnnnnnnnnnnnnnnnnn",
    "mhhhhrhznwvhh",
    "xmxxxxxxx",
    "ppppk",
    "tttttttttttjtcn",
    "qqvhz",
    "gbpqclnkwlhdlml",
    "fffffffffffrf",
    "ssjssssssslssss",
    "bbbbbwbb",
    "krrrrrfrj",
    "bbbbbbbbbvbbbp",
    "ltgbx",
    "smrrrrkjrrr",
    "vnqpngjdgrw",
    "ttltqtsktrjgxtqhtt",
    "dvvxbvvvnk",
    "nnnnnpn",
    "nttmtx",
    "zpszz",
    "pmpxphlpppppppqppp",
    "qvvvvvv",
    "gwgggggggtgqgg",
    "knpn",
    "hncbdrvpddddcfddd",
    "ssnspslslsfkpskss",
    "ssczgkvtlp",
    "pmvpzpppkm",
    "jjhr",
    "ssssxl",
    "ttrt",
    "nnpnnnnnnnnnnnnnnnn",
    "nnfnl",
    "bbbb",
    "nljlllkhl",
    "nnnnnsnnnnnnnpn",
    "kkkkckkkkhkkkkk",
    "zfsssfldxsvqsxdsqs",
    "qqqqqp",
    "qqqqqqq",
    "wwdhmwwjwwwwnwwlwwwv",
    "llllllldll",
    "ccrccccccccrcccccccc",
    "qnwnh",
    "mlll",
    "sssssss",
    "mhclhhhjllhhhgh",
    "xxxxxxtxxxxxtxttxx",
    "rmjh",
    "zzzzzpszt",
    "nnwnnnnnnnnnnnnnppnn",
    "vmvmvlvbvvvvv",
    "bbbbbbdf",
    "kkdkk",
    "dddsldddvxlhd",
    "hhhhkhxshxhn",
    "vcchpxcnmgkctpqcc",
    "wwwwww",
    "xdmk",
    "pbfvrdpqqn",
    "mtnvzhnzs",
    "cttxvtttx",
    "qttmtzttkwftrjk",
    "cccccccccc",
    "zjjqxjfqqlmjrjhjqx",
    "qmkqgq",
    "kkkkkkslzkkkkkrx",
    "hhhhhhhhhqhthhhvhh",
    "hhfhhhhhmhhshhhhhhh",
    "rkrrrrrmrrrrrr",
    "rnnckhmjnxmfggsgtnnn",
    "qsccznccccccnccccccq",
    "wtkck",
    "sssmssjssss",
    "llslv",
    "tvgjqgjbvtgpkt",
    "bbbbbbbbqbblrbbb",
    "zzzzzznzzb",
    "kpcnsccgccxfwccl",
    "ddbd",
    "vvvvqrvvsvvvvvvl",
    "dzdxxhddnlkddddk",
    "khbbbfbbbbb",
    "zzzzzzzzzzzz",
    "bnlvnnrjbnqlnnn",
    "mqqpzjc",
    "hhhhhhchhhhjhh",
    "nxfcxbjqxdlcxxxkxxx",
    "vvbqvvvvvvvvvvvvvvvv",
    "pgtlfffmjffnt",
    "mnkrmmmmmqmmmmmmmjm",
    "lghlhcnwprlgvw",
    "npxplpwl",
    "sfkwnvsssvssssfsssrp",
    "ztqnzlxjmzzbjfnxcw",
    "qqqqqqqqqqqqqqqqqq",
    "jczztzzbhmzzw",
    "skffttjffqfnchfrf",
    "hmqmcrmw",
    "dftttqttttttl",
    "spxnpgtzpppjpwppptp",
    "jqxqqqqxqq",
    "hhhh",
    "pgzxhxxpzzssj",
    "xfrdmjxmrxrqjpxbfxxx",
    "ddpddddddddsgddzddn",
    "vggdggggggggggggggg",
    "mmdqsmwvjjmv",
    "ssqsssk",
    "nnvnnnnnnnnnsgnn",
    "kkkkkkkkkkknkkkk",
    "dprphc",
    "mpkstkxkdb",
    "ssxs",
    "ttjttjttrtsqtmttttt",
    "jrjjtsjjd",
    "xxxpxjx",
    "fqfqqqqhqcqfqqbqqq",
    "zfgrzl",
    "nnnnnphm",
    "bbbbbbbbb",
    "thhgj",
    "vvvcvvvp",
    "ktttttttt",
    "wftbcfnmhkfdpjbns",
    "vvvvvlv",
    "zzzzhfzzzzzzkzzzwzzz",
    "qqqfq",
    "zpjzcppvcppppppppj",
    "vlccbcgcclcczfcfcc",
    "tsntktwzhsfttfwtx",
    "nhhhhhb",
    "bbbphnbbwbbbb",
    "xgxxxlxfxx",
    "mmmmmmmmmmmmmmmm",
    "xxbxx",
    "xkccsfccrccv",
    "jphhbshwghrxpnhnlhxh",
    "nlxbgvftfh",
    "ppwf",
    "kjwjwshcnqwxgwslvl",
    "mmlk",
    "gmgg",
    "rrrvrmr",
    "szgpksczqd",
    "ttttttpjvtqwtltt",
    "hrrrrvrrzj",
    "xmmmmmsmmmcsnmmmmfmm",
    "fffffffffsf",
    "ddddddddddddhdq",
    "jkkkkkkkrkmkkkk",
    "ggggggggg",
    "lllllllvlllllwtx",
    "ggggt",
    "mmkd",
    "jgsgvggwggj",
    "ppppppppppppppphpp",
    "qqjwhq",
    "qqgqqzk",
    "ttwttttttctttthgt",
    "zmmmsm",
    "rrrrrrrrrqrgrrrj",
    "xcvvghvrczpcgn",
    "xbfmxxfxxf",
    "hjbjm",
    "lllltlllllqllll",
    "xsxnxgtx",
    "gggggggggggggggggd",
    "tgttttqtcttttt",
    "pppppd",
    "xxxxxxx",
    "fdcclrccccvg",
    "vnvvvvzdvcrk",
    "zztzqzzzzcz",
    "vmvvvvvvvvvmvvvv",
    "vvvvvvvvvvvvvvvf",
    "xhtsfmvthhhrhdhhbbc",
    "qkccccd",
    "zzzzzzzjzzhbzz",
    "shlnnkxn",
    "vvvvvvvvvvvvvvvvvvcv",
    "hhkhhhkhh",
    "sxslgwvkszswqxtqpvf",
    "mmmmmrmbm",
    "jrnjjzjfhjdkjqjtkwk",
    "ffffffsfffffwfff",
    "wmwwdwwwsz",
    "nsffpfsdsjsfsffk",
    "kkkkkkkkkkkkkkhw",
    "ssssslssssssssssss",
    "srdscnncclqqcncsw",
    "pkppppppppp",
    "qqqqqqqqqpqq",
    "nnnnnnnnnnnnnn",
    "hhhhhqhhhhhvhhhh",
    "fgfrpzcstfffffxff",
    "nnxmnmnnnnknrpmnv",
    "jmmmmcnpkm",
    "mvkcwvmvvjvrvlv",
    "hhrmbrhhhhlhhvhmhhhb",
    "ggggggzgggsgfgxg",
    "pmmxmmmmmmmmmmm",
    "zlmsmlxpvvlzv",
    "sslggkdglqgxpgkx",
    "ccccccccccccccccmc",
    "wwwwwpcwwwpwwd",
    "wwwwk",
    "vfbvffsfcf",
    "rrrrrr",
    "nrnknn",
    "lxllllll",
    "qdfwvfffdfvwffgfkfgf",
    "xgxbdqxbfvzrl",
    "pbbkbbgbxr",
    "ddxdnv",
    "dndfcnhd",
]

policies = [
    ("x", (1, 9)),
    ("r", (4, 6)),
    ("v", (4, 5)),
    ("m", (5, 16)),
    ("s", (15, 16)),
    ("g", (10, 12)),
    ("n", (2, 7)),
    ("j", (11, 14)),
    ("r", (2, 6)),
    ("h", (6, 7)),
    ("w", (4, 5)),
    ("g", (1, 6)),
    ("c", (3, 4)),
    ("k", (5, 8)),
    ("h", (14, 15)),
    ("g", (6, 7)),
    ("r", (1, 3)),
    ("j", (15, 16)),
    ("k", (8, 10)),
    ("s", (1, 4)),
    ("d", (2, 3)),
    ("s", (6, 7)),
    ("z", (8, 9)),
    ("t", (7, 8)),
    ("n", (3, 10)),
    ("z", (5, 7)),
    ("l", (8, 9)),
    ("p", (1, 2)),
    ("d", (2, 5)),
    ("r", (13, 16)),
    ("l", (7, 16)),
    ("z", (9, 14)),
    ("f", (3, 5)),
    ("s", (6, 8)),
    ("r", (9, 18)),
    ("d", (2, 5)),
    ("c", (13, 14)),
    ("z", (9, 10)),
    ("s", (5, 9)),
    ("x", (4, 11)),
    ("t", (4, 6)),
    ("w", (3, 8)),
    ("x", (5, 6)),
    ("w", (2, 7)),
    ("w", (7, 9)),
    ("h", (3, 9)),
    ("p", (1, 4)),
    ("w", (4, 5)),
    ("p", (6, 7)),
    ("m", (2, 16)),
    ("g", (8, 10)),
    ("z", (7, 18)),
    ("t", (10, 11)),
    ("k", (3, 8)),
    ("x", (19, 20)),
    ("l", (9, 16)),
    ("m", (10, 12)),
    ("c", (1, 4)),
    ("n", (7, 10)),
    ("z", (10, 17)),
    ("k", (4, 9)),
    ("m", (12, 13)),
    ("s", (4, 6)),
    ("n", (10, 16)),
    ("w", (2, 3)),
    ("w", (7, 17)),
    ("q", (5, 8)),
    ("p", (9, 10)),
    ("f", (1, 5)),
    ("k", (2, 9)),
    ("n", (9, 11)),
    ("r", (4, 6)),
    ("z", (3, 5)),
    ("r", (17, 18)),
    ("c", (5, 8)),
    ("c", (1, 9)),
    ("x", (9, 10)),
    ("c", (2, 5)),
    ("c", (8, 9)),
    ("l", (4, 8)),
    ("l", (1, 5)),
    ("j", (5, 10)),
    ("v", (5, 10)),
    ("v", (4, 6)),
    ("m", (6, 11)),
    ("q", (6, 9)),
    ("n", (2, 5)),
    ("n", (14, 15)),
    ("m", (3, 4)),
    ("h", (3, 11)),
    ("k", (7, 9)),
    ("g", (11, 15)),
    ("z", (3, 4)),
    ("w", (2, 5)),
    ("j", (9, 14)),
    ("j", (2, 4)),
    ("w", (6, 9)),
    ("l", (1, 3)),
    ("g", (9, 10)),
    ("t", (3, 5)),
    ("k", (5, 7)),
    ("r", (9, 11)),
    ("g", (9, 12)),
    ("b", (1, 5)),
    ("m", (6, 7)),
    ("g", (6, 8)),
    ("v", (12, 15)),
    ("s", (15, 17)),
    ("r", (9, 12)),
    ("d", (1, 3)),
    ("m", (1, 11)),
    ("k", (1, 18)),
    ("h", (5, 9)),
    ("k", (2, 3)),
    ("q", (2, 7)),
    ("s", (1, 9)),
    ("p", (4, 6)),
    ("v", (1, 4)),
    ("z", (10, 11)),
    ("q", (2, 14)),
    ("d", (15, 20)),
    ("m", (11, 15)),
    ("c", (3, 4)),
    ("z", (4, 7)),
    ("x", (5, 6)),
    ("b", (5, 13)),
    ("h", (7, 8)),
    ("f", (8, 11)),
    ("n", (5, 6)),
    ("s", (10, 12)),
    ("s", (15, 16)),
    ("s", (4, 5)),
    ("g", (3, 4)),
    ("c", (3, 4)),
    ("v", (7, 12)),
    ("n", (4, 10)),
    ("d", (7, 15)),
    ("h", (6, 10)),
    ("c", (8, 9)),
    ("h", (9, 10)),
    ("w", (2, 16)),
    ("k", (10, 13)),
    ("f", (4, 9)),
    ("v", (4, 11)),
    ("l", (2, 5)),
    ("l", (7, 10)),
    ("g", (10, 19)),
    ("d", (3, 8)),
    ("m", (3, 5)),
    ("n", (13, 14)),
    ("b", (3, 8)),
    ("g", (2, 4)),
    ("m", (8, 11)),
    ("j", (9, 12)),
    ("r", (6, 7)),
    ("v", (8, 13)),
    ("p", (4, 17)),
    ("h", (2, 3)),
    ("c", (2, 15)),
    ("j", (12, 13)),
    ("p", (4, 10)),
    ("r", (5, 8)),
    ("q", (7, 10)),
    ("k", (8, 12)),
    ("m", (3, 14)),
    ("t", (3, 12)),
    ("b", (14, 15)),
    ("f", (14, 15)),
    ("j", (5, 16)),
    ("v", (7, 8)),
    ("m", (2, 11)),
    ("m", (11, 12)),
    ("n", (6, 7)),
    ("m", (4, 8)),
    ("m", (4, 7)),
    ("w", (1, 4)),
    ("j", (12, 14)),
    ("h", (2, 9)),
    ("v", (2, 11)),
    ("f", (6, 7)),
    ("k", (3, 14)),
    ("c", (1, 2)),
    ("z", (15, 17)),
    ("p", (4, 13)),
    ("j", (4, 5)),
    ("h", (14, 20)),
    ("j", (1, 3)),
    ("x", (9, 13)),
    ("w", (13, 14)),
    ("p", (2, 5)),
    ("x", (13, 15)),
    ("q", (5, 11)),
    ("q", (8, 12)),
    ("m", (8, 10)),
    ("t", (17, 18)),
    ("h", (9, 13)),
    ("s", (8, 9)),
    ("v", (9, 10)),
    ("d", (7, 12)),
    ("z", (2, 3)),
    ("k", (1, 4)),
    ("d", (1, 9)),
    ("h", (10, 11)),
    ("f", (9, 10)),
    ("d", (4, 7)),
    ("j", (18, 19)),
    ("m", (7, 11)),
    ("k", (1, 7)),
    ("w", (4, 5)),
    ("s", (6, 13)),
    ("z", (4, 5)),
    ("j", (9, 11)),
    ("h", (4, 7)),
    ("v", (5, 14)),
    ("q", (5, 6)),
    ("q", (1, 5)),
    ("z", (5, 7)),
    ("s", (5, 9)),
    ("f", (4, 5)),
    ("b", (5, 7)),
    ("j", (1, 14)),
    ("w", (8, 10)),
    ("g", (3, 6)),
    ("n", (11, 14)),
    ("c", (6, 15)),
    ("l", (5, 8)),
    ("p", (4, 11)),
    ("w", (1, 4)),
    ("g", (1, 3)),
    ("w", (11, 12)),
    ("j", (4, 12)),
    ("r", (1, 2)),
    ("k", (1, 4)),
    ("d", (11, 13)),
    ("r", (1, 4)),
    ("m", (8, 9)),
    ("x", (1, 2)),
    ("n", (4, 16)),
    ("g", (2, 10)),
    ("p", (11, 19)),
    ("g", (9, 13)),
    ("m", (4, 5)),
    ("t", (2, 13)),
    ("q", (3, 7)),
    ("j", (6, 9)),
    ("r", (7, 10)),
    ("r", (9, 12)),
    ("j", (6, 7)),
    ("m", (6, 7)),
    ("m", (1, 3)),
    ("f", (10, 11)),
    ("f", (5, 17)),
    ("b", (4, 5)),
    ("g", (14, 16)),
    ("s", (2, 3)),
    ("g", (5, 10)),
    ("p", (5, 6)),
    ("j", (3, 8)),
    ("c", (2, 4)),
    ("l", (6, 7)),
    ("p", (1, 2)),
    ("g", (16, 17)),
    ("f", (3, 14)),
    ("b", (16, 18)),
    ("v", (5, 10)),
    ("p", (13, 14)),
    ("t", (11, 14)),
    ("w", (3, 4)),
    ("f", (4, 6)),
    ("h", (4, 6)),
    ("t", (15, 17)),
    ("j", (10, 17)),
    ("s", (2, 4)),
    ("q", (7, 9)),
    ("p", (2, 3)),
    ("c", (2, 5)),
    ("d", (1, 7)),
    ("c", (8, 9)),
    ("f", (6, 9)),
    ("s", (13, 15)),
    ("s", (6, 8)),
    ("f", (7, 10)),
    ("k", (1, 6)),
    ("t", (11, 12)),
    ("d", (9, 16)),
    ("v", (18, 19)),
    ("j", (2, 5)),
    ("d", (11, 12)),
    ("f", (14, 16)),
    ("x", (4, 7)),
    ("p", (10, 18)),
    ("k", (8, 9)),
    ("h", (9, 15)),
    ("v", (18, 19)),
    ("s", (1, 8)),
    ("p", (2, 6)),
    ("n", (6, 7)),
    ("j", (2, 7)),
    ("b", (11, 12)),
    ("z", (4, 5)),
    ("x", (4, 9)),
    ("w", (9, 12)),
    ("k", (2, 5)),
    ("l", (10, 12)),
    ("t", (1, 4)),
    ("d", (6, 7)),
    ("h", (2, 6)),
    ("c", (5, 8)),
    ("r", (5, 6)),
    ("h", (3, 8)),
    ("s", (2, 4)),
    ("m", (2, 7)),
    ("n", (7, 9)),
    ("f", (6, 7)),
    ("h", (6, 8)),
    ("j", (6, 7)),
    ("r", (1, 5)),
    ("t", (3, 4)),
    ("k", (2, 7)),
    ("q", (6, 11)),
    ("l", (5, 7)),
    ("r", (6, 14)),
    ("w", (1, 8)),
    ("b", (3, 13)),
    ("d", (6, 9)),
    ("n", (14, 15)),
    ("k", (2, 18)),
    ("w", (5, 14)),
    ("s", (5, 7)),
    ("l", (1, 18)),
    ("h", (1, 17)),
    ("w", (7, 13)),
    ("r", (1, 3)),
    ("t", (9, 11)),
    ("c", (2, 12)),
    ("q", (4, 13)),
    ("d", (2, 9)),
    ("p", (9, 19)),
    ("l", (8, 9)),
    ("h", (7, 8)),
    ("w", (11, 12)),
    ("d", (2, 3)),
    ("n", (13, 16)),
    ("d", (6, 7)),
    ("n", (6, 7)),
    ("v", (7, 14)),
    ("j", (5, 7)),
    ("l", (4, 10)),
    ("x", (4, 5)),
    ("q", (15, 16)),
    ("m", (13, 15)),
    ("k", (7, 10)),
    ("m", (9, 15)),
    ("t", (2, 4)),
    ("s", (6, 7)),
    ("n", (3, 4)),
    ("l", (1, 3)),
    ("l", (5, 6)),
    ("s", (4, 5)),
    ("t", (7, 9)),
    ("l", (1, 3)),
    ("c", (6, 10)),
    ("k", (1, 3)),
    ("h", (2, 4)),
    ("s", (16, 17)),
    ("p", (4, 8)),
    ("k", (5, 10)),
    ("s", (4, 11)),
    ("j", (6, 14)),
    ("t", (3, 7)),
    ("l", (7, 8)),
    ("z", (4, 11)),
    ("x", (2, 11)),
    ("m", (11, 15)),
    ("l", (10, 13)),
    ("k", (5, 6)),
    ("f", (4, 7)),
    ("b", (1, 9)),
    ("h", (10, 12)),
    ("r", (1, 8)),
    ("b", (16, 20)),
    ("c", (1, 5)),
    ("c", (6, 13)),
    ("j", (13, 14)),
    ("j", (2, 4)),
    ("d", (2, 7)),
    ("r", (5, 6)),
    ("l", (7, 8)),
    ("w", (2, 3)),
    ("v", (9, 12)),
    ("s", (6, 16)),
    ("z", (5, 17)),
    ("j", (12, 17)),
    ("s", (8, 10)),
    ("m", (2, 6)),
    ("m", (9, 11)),
    ("p", (14, 16)),
    ("d", (4, 15)),
    ("q", (12, 14)),
    ("g", (1, 6)),
    ("w", (10, 18)),
    ("t", (8, 9)),
    ("j", (3, 5)),
    ("c", (17, 18)),
    ("d", (4, 9)),
    ("x", (2, 4)),
    ("v", (11, 12)),
    ("z", (1, 4)),
    ("h", (4, 5)),
    ("t", (3, 6)),
    ("k", (7, 15)),
    ("w", (12, 15)),
    ("z", (3, 5)),
    ("n", (5, 6)),
    ("b", (1, 3)),
    ("r", (1, 10)),
    ("w", (11, 12)),
    ("j", (5, 6)),
    ("h", (6, 11)),
    ("q", (18, 19)),
    ("l", (17, 18)),
    ("j", (3, 4)),
    ("z", (8, 10)),
    ("t", (6, 7)),
    ("f", (11, 12)),
    ("b", (2, 8)),
    ("w", (4, 5)),
    ("z", (1, 2)),
    ("w", (6, 8)),
    ("z", (8, 14)),
    ("b", (4, 11)),
    ("d", (2, 9)),
    ("x", (3, 6)),
    ("n", (15, 16)),
    ("x", (6, 11)),
    ("s", (1, 12)),
    ("m", (1, 16)),
    ("t", (3, 15)),
    ("z", (9, 17)),
    ("f", (4, 6)),
    ("d", (3, 9)),
    ("k", (6, 10)),
    ("n", (6, 7)),
    ("t", (7, 13)),
    ("r", (7, 10)),
    ("c", (2, 3)),
    ("m", (5, 7)),
    ("j", (3, 5)),
    ("s", (5, 6)),
    ("c", (16, 18)),
    ("b", (7, 16)),
    ("b", (6, 8)),
    ("h", (1, 10)),
    ("s", (4, 6)),
    ("g", (3, 4)),
    ("c", (4, 7)),
    ("m", (1, 13)),
    ("j", (1, 2)),
    ("w", (9, 10)),
    ("h", (2, 4)),
    ("j", (7, 10)),
    ("f", (3, 7)),
    ("b", (3, 4)),
    ("n", (3, 5)),
    ("f", (7, 8)),
    ("k", (10, 12)),
    ("k", (9, 10)),
    ("z", (4, 6)),
    ("v", (4, 7)),
    ("z", (6, 12)),
    ("s", (6, 8)),
    ("b", (5, 7)),
    ("d", (1, 3)),
    ("b", (3, 4)),
    ("r", (5, 8)),
    ("m", (7, 8)),
    ("q", (9, 11)),
    ("w", (3, 4)),
    ("q", (1, 3)),
    ("q", (1, 2)),
    ("s", (6, 12)),
    ("q", (2, 4)),
    ("c", (5, 6)),
    ("x", (14, 15)),
    ("f", (6, 12)),
    ("g", (14, 17)),
    ("n", (5, 8)),
    ("d", (10, 13)),
    ("c", (2, 4)),
    ("s", (2, 10)),
    ("q", (6, 12)),
    ("n", (6, 16)),
    ("s", (6, 12)),
    ("v", (1, 4)),
    ("h", (8, 10)),
    ("t", (1, 4)),
    ("k", (1, 4)),
    ("q", (1, 2)),
    ("n", (9, 19)),
    ("h", (15, 16)),
    ("g", (2, 5)),
    ("c", (12, 13)),
    ("g", (1, 13)),
    ("g", (14, 17)),
    ("s", (4, 14)),
    ("d", (1, 10)),
    ("g", (4, 14)),
    ("z", (8, 10)),
    ("t", (5, 10)),
    ("v", (3, 5)),
    ("w", (9, 10)),
    ("c", (4, 6)),
    ("s", (16, 18)),
    ("z", (2, 7)),
    ("v", (4, 10)),
    ("d", (10, 16)),
    ("v", (3, 4)),
    ("h", (3, 4)),
    ("b", (3, 5)),
    ("m", (3, 5)),
    ("q", (4, 17)),
    ("m", (6, 17)),
    ("r", (1, 3)),
    ("j", (3, 5)),
    ("q", (11, 12)),
    ("d", (8, 11)),
    ("d", (3, 16)),
    ("z", (7, 13)),
    ("h", (6, 18)),
    ("n", (4, 5)),
    ("d", (16, 17)),
    ("w", (14, 16)),
    ("t", (2, 3)),
    ("s", (3, 4)),
    ("j", (1, 9)),
    ("p", (1, 2)),
    ("k", (9, 14)),
    ("x", (1, 5)),
    ("p", (1, 14)),
    ("d", (5, 12)),
    ("v", (9, 10)),
    ("x", (2, 7)),
    ("c", (3, 15)),
    ("w", (5, 8)),
    ("w", (7, 14)),
    ("r", (5, 10)),
    ("f", (7, 12)),
    ("h", (2, 6)),
    ("x", (3, 13)),
    ("k", (4, 8)),
    ("g", (7, 10)),
    ("s", (8, 9)),
    ("l", (6, 10)),
    ("c", (8, 11)),
    ("x", (5, 6)),
    ("w", (1, 3)),
    ("v", (8, 11)),
    ("b", (1, 2)),
    ("b", (7, 10)),
    ("t", (13, 15)),
    ("x", (12, 14)),
    ("k", (6, 7)),
    ("m", (4, 5)),
    ("t", (2, 3)),
    ("x", (4, 5)),
    ("m", (1, 3)),
    ("c", (10, 11)),
    ("b", (14, 19)),
    ("x", (9, 10)),
    ("g", (4, 5)),
    ("k", (8, 12)),
    ("v", (2, 6)),
    ("r", (4, 10)),
    ("n", (4, 6)),
    ("v", (3, 10)),
    ("w", (10, 13)),
    ("w", (18, 20)),
    ("w", (7, 8)),
    ("q", (16, 17)),
    ("k", (2, 5)),
    ("b", (3, 4)),
    ("v", (5, 8)),
    ("t", (3, 15)),
    ("t", (1, 6)),
    ("w", (5, 6)),
    ("m", (3, 5)),
    ("n", (11, 17)),
    ("m", (5, 6)),
    ("r", (1, 7)),
    ("m", (6, 16)),
    ("s", (5, 10)),
    ("p", (9, 14)),
    ("l", (2, 4)),
    ("g", (6, 17)),
    ("z", (5, 7)),
    ("q", (4, 5)),
    ("h", (10, 19)),
    ("m", (6, 7)),
    ("m", (2, 3)),
    ("j", (8, 10)),
    ("x", (3, 6)),
    ("z", (6, 7)),
    ("k", (8, 17)),
    ("n", (6, 9)),
    ("m", (6, 8)),
    ("q", (4, 6)),
    ("s", (2, 8)),
    ("r", (6, 7)),
    ("h", (2, 5)),
    ("b", (5, 15)),
    ("d", (12, 13)),
    ("f", (5, 6)),
    ("j", (4, 7)),
    ("g", (6, 9)),
    ("b", (9, 12)),
    ("s", (1, 8)),
    ("f", (10, 14)),
    ("p", (13, 17)),
    ("n", (16, 17)),
    ("k", (10, 16)),
    ("w", (8, 11)),
    ("q", (2, 5)),
    ("m", (2, 7)),
    ("m", (2, 9)),
    ("s", (3, 9)),
    ("z", (12, 16)),
    ("f", (6, 7)),
    ("g", (2, 3)),
    ("f", (2, 3)),
    ("h", (1, 8)),
    ("x", (6, 12)),
    ("w", (4, 5)),
    ("r", (7, 10)),
    ("q", (6, 10)),
    ("v", (5, 18)),
    ("z", (6, 9)),
    ("x", (3, 6)),
    ("l", (8, 9)),
    ("k", (1, 4)),
    ("q", (2, 6)),
    ("m", (4, 7)),
    ("r", (4, 5)),
    ("c", (1, 8)),
    ("m", (6, 7)),
    ("t", (2, 4)),
    ("s", (9, 10)),
    ("b", (4, 18)),
    ("f", (4, 5)),
    ("l", (3, 6)),
    ("l", (1, 5)),
    ("l", (15, 19)),
    ("j", (10, 11)),
    ("w", (2, 3)),
    ("r", (1, 7)),
    ("k", (3, 7)),
    ("k", (9, 12)),
    ("b", (1, 6)),
    ("s", (6, 8)),
    ("x", (2, 4)),
    ("x", (6, 10)),
    ("x", (7, 8)),
    ("n", (6, 19)),
    ("q", (2, 5)),
    ("j", (15, 17)),
    ("x", (5, 7)),
    ("t", (3, 6)),
    ("f", (8, 11)),
    ("r", (6, 8)),
    ("m", (10, 12)),
    ("z", (13, 14)),
    ("c", (19, 20)),
    ("z", (7, 12)),
    ("z", (12, 14)),
    ("s", (1, 2)),
    ("q", (1, 3)),
    ("z", (1, 6)),
    ("b", (9, 11)),
    ("s", (4, 6)),
    ("j", (2, 5)),
    ("l", (7, 16)),
    ("f", (2, 3)),
    ("w", (7, 15)),
    ("z", (2, 4)),
    ("h", (5, 6)),
    ("h", (13, 14)),
    ("k", (16, 17)),
    ("l", (7, 15)),
    ("w", (2, 6)),
    ("k", (2, 7)),
    ("d", (7, 9)),
    ("v", (4, 9)),
    ("m", (6, 11)),
    ("p", (3, 8)),
    ("f", (2, 6)),
    ("v", (8, 11)),
    ("h", (5, 17)),
    ("f", (8, 10)),
    ("s", (9, 12)),
    ("m", (9, 12)),
    ("l", (7, 9)),
    ("m", (8, 11)),
    ("m", (1, 4)),
    ("c", (13, 14)),
    ("f", (5, 9)),
    ("f", (5, 8)),
    ("m", (3, 8)),
    ("m", (1, 6)),
    ("h", (1, 2)),
    ("d", (4, 14)),
    ("c", (6, 7)),
    ("v", (6, 12)),
    ("d", (11, 14)),
    ("f", (2, 13)),
    ("c", (10, 13)),
    ("q", (17, 19)),
    ("t", (8, 10)),
    ("f", (4, 5)),
    ("v", (2, 16)),
    ("c", (2, 4)),
    ("z", (3, 8)),
    ("k", (6, 10)),
    ("r", (5, 7)),
    ("w", (14, 15)),
    ("q", (6, 11)),
    ("f", (4, 7)),
    ("t", (2, 14)),
    ("t", (11, 15)),
    ("c", (6, 10)),
    ("s", (3, 8)),
    ("h", (1, 8)),
    ("b", (13, 15)),
    ("p", (15, 17)),
    ("l", (5, 12)),
    ("v", (2, 4)),
    ("k", (3, 5)),
    ("z", (6, 12)),
    ("j", (2, 3)),
    ("r", (6, 7)),
    ("t", (1, 12)),
    ("z", (10, 13)),
    ("s", (5, 13)),
    ("m", (10, 14)),
    ("b", (2, 5)),
    ("h", (2, 15)),
    ("c", (1, 4)),
    ("b", (9, 10)),
    ("j", (4, 5)),
    ("n", (3, 6)),
    ("m", (11, 12)),
    ("r", (2, 4)),
    ("g", (3, 4)),
    ("n", (14, 17)),
    ("k", (4, 5)),
    ("h", (11, 17)),
    ("q", (5, 19)),
    ("t", (5, 16)),
    ("h", (11, 18)),
    ("c", (5, 8)),
    ("v", (1, 3)),
    ("m", (7, 12)),
    ("r", (15, 16)),
    ("b", (7, 19)),
    ("w", (10, 13)),
    ("p", (5, 15)),
    ("n", (2, 4)),
    ("s", (5, 11)),
    ("q", (12, 16)),
    ("j", (2, 7)),
    ("s", (6, 7)),
    ("t", (1, 4)),
    ("q", (5, 10)),
    ("q", (11, 15)),
    ("k", (3, 5)),
    ("f", (14, 15)),
    ("x", (4, 5)),
    ("b", (2, 4)),
    ("t", (3, 4)),
    ("s", (1, 3)),
    ("z", (8, 12)),
    ("f", (1, 3)),
    ("s", (5, 8)),
    ("v", (7, 17)),
    ("k", (4, 5)),
    ("h", (8, 17)),
    ("n", (17, 18)),
    ("h", (3, 10)),
    ("x", (8, 9)),
    ("p", (4, 5)),
    ("t", (11, 13)),
    ("q", (3, 4)),
    ("l", (3, 8)),
    ("f", (12, 13)),
    ("s", (3, 11)),
    ("b", (6, 7)),
    ("r", (7, 9)),
    ("b", (13, 14)),
    ("x", (2, 4)),
    ("r", (7, 10)),
    ("n", (3, 7)),
    ("t", (7, 18)),
    ("v", (2, 5)),
    ("n", (2, 5)),
    ("t", (1, 3)),
    ("z", (3, 4)),
    ("p", (1, 12)),
    ("v", (3, 4)),
    ("g", (9, 12)),
    ("n", (2, 4)),
    ("d", (3, 13)),
    ("s", (5, 9)),
    ("s", (1, 2)),
    ("p", (5, 6)),
    ("j", (1, 4)),
    ("s", (5, 6)),
    ("t", (1, 3)),
    ("n", (16, 18)),
    ("n", (4, 5)),
    ("b", (1, 4)),
    ("l", (7, 8)),
    ("n", (11, 12)),
    ("k", (5, 10)),
    ("s", (7, 10)),
    ("q", (5, 6)),
    ("q", (6, 7)),
    ("w", (14, 16)),
    ("l", (8, 9)),
    ("c", (12, 14)),
    ("n", (1, 3)),
    ("l", (1, 4)),
    ("s", (1, 3)),
    ("h", (4, 15)),
    ("x", (15, 16)),
    ("r", (2, 4)),
    ("z", (6, 9)),
    ("n", (17, 18)),
    ("v", (8, 11)),
    ("b", (7, 8)),
    ("k", (2, 5)),
    ("d", (8, 9)),
    ("h", (7, 8)),
    ("c", (12, 14)),
    ("w", (1, 5)),
    ("x", (1, 2)),
    ("p", (1, 9)),
    ("s", (2, 4)),
    ("t", (4, 6)),
    ("t", (4, 8)),
    ("c", (7, 9)),
    ("j", (2, 18)),
    ("q", (2, 5)),
    ("k", (5, 11)),
    ("h", (16, 18)),
    ("h", (5, 13)),
    ("r", (10, 12)),
    ("n", (8, 10)),
    ("c", (19, 20)),
    ("k", (1, 4)),
    ("s", (7, 8)),
    ("l", (3, 5)),
    ("t", (3, 7)),
    ("b", (13, 15)),
    ("z", (9, 10)),
    ("c", (6, 16)),
    ("d", (2, 3)),
    ("v", (10, 16)),
    ("d", (3, 12)),
    ("b", (8, 9)),
    ("z", (11, 12)),
    ("n", (5, 15)),
    ("q", (1, 2)),
    ("h", (11, 13)),
    ("x", (8, 11)),
    ("v", (14, 18)),
    ("f", (7, 8)),
    ("m", (10, 18)),
    ("l", (1, 4)),
    ("p", (3, 4)),
    ("s", (12, 15)),
    ("z", (3, 7)),
    ("q", (17, 18)),
    ("z", (3, 6)),
    ("f", (3, 7)),
    ("m", (4, 6)),
    ("t", (10, 11)),
    ("p", (7, 13)),
    ("q", (8, 9)),
    ("h", (3, 4)),
    ("z", (10, 13)),
    ("x", (5, 9)),
    ("d", (8, 17)),
    ("g", (1, 4)),
    ("m", (10, 12)),
    ("s", (2, 7)),
    ("n", (13, 14)),
    ("k", (2, 16)),
    ("p", (3, 6)),
    ("k", (2, 10)),
    ("s", (2, 3)),
    ("t", (9, 19)),
    ("j", (4, 5)),
    ("x", (6, 7)),
    ("q", (13, 15)),
    ("z", (1, 3)),
    ("n", (6, 8)),
    ("b", (1, 8)),
    ("h", (4, 5)),
    ("v", (4, 8)),
    ("t", (8, 9)),
    ("f", (3, 4)),
    ("v", (6, 7)),
    ("z", (16, 17)),
    ("q", (1, 2)),
    ("p", (10, 11)),
    ("c", (10, 15)),
    ("t", (11, 17)),
    ("h", (1, 7)),
    ("b", (6, 13)),
    ("x", (8, 9)),
    ("m", (14, 16)),
    ("x", (3, 4)),
    ("c", (6, 9)),
    ("h", (10, 18)),
    ("f", (6, 10)),
    ("p", (3, 4)),
    ("s", (1, 6)),
    ("m", (2, 3)),
    ("g", (2, 3)),
    ("r", (3, 6)),
    ("s", (1, 6)),
    ("t", (12, 14)),
    ("r", (1, 2)),
    ("m", (1, 13)),
    ("f", (10, 11)),
    ("d", (13, 15)),
    ("k", (7, 14)),
    ("g", (6, 9)),
    ("l", (14, 16)),
    ("g", (1, 3)),
    ("m", (3, 4)),
    ("g", (5, 10)),
    ("p", (17, 18)),
    ("q", (1, 2)),
    ("q", (2, 6)),
    ("t", (11, 16)),
    ("m", (1, 5)),
    ("r", (12, 16)),
    ("v", (4, 5)),
    ("x", (1, 3)),
    ("j", (3, 5)),
    ("l", (5, 14)),
    ("x", (3, 4)),
    ("g", (6, 18)),
    ("t", (8, 12)),
    ("p", (4, 6)),
    ("x", (6, 7)),
    ("c", (3, 4)),
    ("v", (11, 12)),
    ("z", (1, 9)),
    ("v", (1, 12)),
    ("v", (9, 16)),
    ("h", (2, 7)),
    ("c", (5, 6)),
    ("z", (8, 12)),
    ("n", (2, 4)),
    ("v", (19, 20)),
    ("h", (7, 8)),
    ("p", (5, 19)),
    ("m", (5, 8)),
    ("j", (2, 5)),
    ("f", (7, 13)),
    ("w", (6, 9)),
    ("f", (12, 15)),
    ("k", (13, 16)),
    ("s", (6, 17)),
    ("c", (3, 5)),
    ("p", (9, 11)),
    ("q", (5, 10)),
    ("n", (12, 14)),
    ("h", (6, 11)),
    ("f", (2, 12)),
    ("n", (2, 12)),
    ("m", (6, 7)),
    ("v", (4, 6)),
    ("h", (18, 20)),
    ("g", (9, 13)),
    ("m", (9, 15)),
    ("l", (1, 7)),
    ("g", (2, 15)),
    ("c", (17, 18)),
    ("w", (10, 11)),
    ("w", (3, 5)),
    ("f", (8, 9)),
    ("r", (4, 6)),
    ("n", (2, 4)),
    ("l", (1, 4)),
    ("f", (10, 11)),
    ("b", (3, 4)),
    ("b", (2, 8)),
    ("d", (1, 2)),
    ("d", (4, 8)),
]

assert len(passwords) == len(policies)
print(len(passwords))

def char_count(password, policy_char):
    return len([c for c in password if c == policy_char])

valid_count = 0

for i, p in enumerate(passwords):
    if policies[i][1][0] <= char_count(p, policies[i][0]) <= policies[i][1][1]:
        valid_count += 1

print(valid_count)